


import java.util.*;
import java.lang.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DragonDream
 */
public class MainFrame extends javax.swing.JFrame {
    

    
    /**
     * Creates new form Stacks_ui
     */
    public MainFrame() {
        initComponents();
        
        Stack<String> stack = new Stack<String>();
        stack.push("bottom");
        printStack(stack);
        
        stack.push("next");
        printStack(stack);
        
    } // end main
    
    
    private static void printStack(Stack<String> s){
        // move this to linkedStack class
        if(s.isEmpty()){  
            System.out.println("you've nothing in your stack");
        } 
        else { 
            System.out.printf("%s TOP\n", s); 
        }
        /* Notes:
        %s means it will print a string, 
        %c single character, 
        %d integer based number, 
        %f float based number. 
        String a = "hello"; 
        Character b = 'r'; 
        Integer c = 3; 
        Double d = 3.14; 
        System.out.printf("%s\t%c\n%d\t%f\n", a, b, c, d); 
        also \t put a tabulator and \n make a new line.﻿
        */  
    } // end printStack
    

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jta = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        studID_txtF = new javax.swing.JTextField();
        fName_txtF = new javax.swing.JTextField();
        lastN_txtF = new javax.swing.JTextField();
        age_txtF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        checkEmpty_Btn = new javax.swing.JButton();
        searchName_Btn = new javax.swing.JButton();
        print_Btn = new javax.swing.JButton();
        insTop_Btn = new javax.swing.JButton();
        delALL_Btn = new javax.swing.JButton();
        remTop_Btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sub_txtF1 = new javax.swing.JTextField();
        sub_txtF2 = new javax.swing.JTextField();
        sub_txtF3 = new javax.swing.JTextField();
        sub_txtF4 = new javax.swing.JTextField();
        sub_txtF5 = new javax.swing.JTextField();
        sub_txtF6 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        displayRecord_txtLabel = new javax.swing.JLabel();
        countItems_label = new javax.swing.JLabel();
        nodeItem_txtFd = new javax.swing.JTextField();
        stackCounter_txtFd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        studID_txtF.setText("studID");

        fName_txtF.setText("fName");

        lastN_txtF.setText("lastName");

        age_txtF.setText("age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studID_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fName_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastN_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(age_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studID_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fName_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastN_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        checkEmpty_Btn.setText("Check if Empty");
        checkEmpty_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmpty_BtnActionPerformed(evt);
            }
        });

        searchName_Btn.setText("Search by Name");

        print_Btn.setText("Print Contents");

        insTop_Btn.setText("Insert TOP");
        insTop_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insTop_BtnActionPerformed(evt);
            }
        });

        delALL_Btn.setText("Clear ALL ITEMS");

        remTop_Btn.setText("Remove TOP");
        remTop_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remTop_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchName_Btn)
                            .addComponent(checkEmpty_Btn))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(insTop_Btn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(remTop_Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delALL_Btn))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(print_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEmpty_Btn)
                    .addComponent(remTop_Btn)
                    .addComponent(delALL_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchName_Btn)
                    .addComponent(insTop_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        sub_txtF1.setText("Subject1");
        sub_txtF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_txtF1ActionPerformed(evt);
            }
        });

        sub_txtF2.setText("Subject2");

        sub_txtF3.setText("Subject3");

        sub_txtF4.setText("Subject4");
        sub_txtF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_txtF4ActionPerformed(evt);
            }
        });

        sub_txtF5.setText("Subject5");

        sub_txtF6.setText("Subject6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sub_txtF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_txtF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_txtF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_txtF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_txtF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sub_txtF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub_txtF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_txtF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_txtF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_txtF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_txtF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub_txtF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        displayRecord_txtLabel.setText("Display Records for current Student");

        countItems_label.setText("No. of Items in Stack");

        nodeItem_txtFd.setText("Node");

        stackCounter_txtFd.setText("count");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stackCounter_txtFd)
                    .addComponent(nodeItem_txtFd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countItems_label)
                    .addComponent(displayRecord_txtLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeItem_txtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayRecord_txtLabel))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stackCounter_txtFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countItems_label))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jta, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jta, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remTop_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remTop_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remTop_BtnActionPerformed

    private void sub_txtF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_txtF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_txtF4ActionPerformed

    private void sub_txtF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_txtF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_txtF1ActionPerformed

    private void insTop_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insTop_BtnActionPerformed
        // inserts new Node (data contains Student Object which is an arrayList) on top of Stack
        // first enter new Data to Student Class
        String studIdInput = JOptionPane.showInputDialog("enter Student ID");
            int studIdIn = Integer.parseInt(studIdInput);
            System.out.println("You've entered Student ID : " + studIdInput);
            
        String fNameInput = JOptionPane.showInputDialog("enter First Name");
            System.out.println("You've entered First Name : " + fNameInput);
            
        String lNameInput = JOptionPane.showInputDialog("enter Last Name");
            System.out.println("You've entered Last Name : " + lNameInput);
            
        String ageInput = JOptionPane.showInputDialog("enter First Name");
            int ageIn = Integer.parseInt(ageInput);
            System.out.println("You've entered Age : " + ageIn);
            
        String gradeInput1 = JOptionPane.showInputDialog("enter results for Exam 1");
            int gradeIn1 = Integer.parseInt(gradeInput1);
            System.out.println("You've entered Grade 1 : " + gradeIn1);  
            
        String gradeInput2 = JOptionPane.showInputDialog("enter results for Exam 1");
            int gradeIn2 = Integer.parseInt(gradeInput2);
            System.out.println("You've entered Grade 2 : " + gradeInput2);
            
        String gradeInput3 = JOptionPane.showInputDialog("enter results for Exam 1");
            int gradeIn3 = Integer.parseInt(gradeInput3);
            System.out.println("You've entered Grade 3 : " + gradeIn3);
         
        String gradeInput4 = JOptionPane.showInputDialog("enter results for Exam 1");
            int gradeIn4 = Integer.parseInt(gradeInput4);
            System.out.println("You've entered Grade 4 : " + gradeIn4);
            
        String gradeInput5 = JOptionPane.showInputDialog("enter results for Exam 1");
            int gradeIn5 = Integer.parseInt(gradeInput5);
            System.out.println("You've entered Grade 5 : " + gradeIn5);
            
        String gradeInput6 = JOptionPane.showInputDialog("enter results for Exam 1");
            int gradeIn6 = Integer.parseInt(gradeInput6);
            System.out.println("You've entered Grade 6 : " + gradeIn6);
        //create new Student Object
        Student newStudentElement = new Student(studIdIn, fNameInput, lNameInput, ageIn, gradeIn1, gradeIn2, gradeIn3, gradeIn4, gradeIn5, gradeIn6 );
    }//GEN-LAST:event_insTop_BtnActionPerformed

    private void checkEmpty_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmpty_BtnActionPerformed
        // CHECK if stack is empty
        // to call a non static method from another (not private) class in same package
        // ref: http://stackoverflow.com/questions/31086487/i-want-to-call-a-method-from-another-class-but-in-same-package-or-file-how-to-do
        LinkedStack link = new LinkedStack();
        link.isEmpty();    
    }//GEN-LAST:event_checkEmpty_BtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // when the Form is closed, exit
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_txtF;
    private javax.swing.JButton checkEmpty_Btn;
    private javax.swing.JLabel countItems_label;
    private javax.swing.JButton delALL_Btn;
    private javax.swing.JLabel displayRecord_txtLabel;
    private javax.swing.JTextField fName_txtF;
    private javax.swing.JButton insTop_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.TextArea jta;
    private javax.swing.JTextField lastN_txtF;
    private javax.swing.JTextField nodeItem_txtFd;
    private javax.swing.JButton print_Btn;
    private javax.swing.JButton remTop_Btn;
    private javax.swing.JButton searchName_Btn;
    private javax.swing.JTextField stackCounter_txtFd;
    private javax.swing.JTextField studID_txtF;
    private javax.swing.JTextField sub_txtF1;
    private javax.swing.JTextField sub_txtF2;
    private javax.swing.JTextField sub_txtF3;
    private javax.swing.JTextField sub_txtF4;
    private javax.swing.JTextField sub_txtF5;
    private javax.swing.JTextField sub_txtF6;
    // End of variables declaration//GEN-END:variables
}
